[package]
name = "cwillsey/stand-controller"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
trove = "sleitnick/trove@0.3.0"
knit = "sleitnick/knit@1.4.4"