[package]
name = "cwillsey/stand-controller"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
contextcontrols = "vocksel/context-controls@1.0.1"
promise = "evaera/promise@4.0.0"
trove = "sleitnick/trove@0.3.0"